# Generated by Django 5.0.4 on 2024-04-25 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_ticker_remove_customuser_groups_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userstickers",
            old_name="symbol",
            new_name="tickers",
        ),
    ]
